define("wkcommon:widget/node_modules/@baidu/el-visible/index.js",function(t,e,i){var n=window.$,o={onElsVisible:function(t,e){function i(){try{n(t).each(function(t,i){var o=i.getBoundingClientRect(),c=o.top,l=o.bottom,d=document.documentElement.clientHeight,s=n(i).data("visiblePre");s||(d>=c&&l>=0&&n(i).is(":visible")?(n(i).data({visiblePre:!0}),n.isFunction(e)&&e.apply(i)):(c>d||0>l)&&n(i).data({visiblePre:!1}))})}catch(i){}}n(document).on("scroll",i),n(document).trigger("scroll")},onAutoActElVisible:function(t,e){function i(){try{if("string"==typeof t&&(t=n(t)[0]),void 0===t)return;
var i=t.getBoundingClientRect().top,o=t.getBoundingClientRect().bottom,c=document.documentElement.clientHeight,l=n(t).data("visiblePre");if(l)return;c>=i&&o>=0&&n(t).is(":visible")?(n(t).data({visiblePre:!0}),n.isFunction(e)&&e()):(i>c||0>o)&&n(t).data({visiblePre:!1})}catch(d){}}n(document).on("scroll",i)}};i.exports=o});
;define("wkcommon:widget/node_modules/@baidu/npm-wk-performance/index.js",function(e,t,n){var r=function(e,t){var n=window.performance;if(!n)return{msg:"not suport performance"};var r=n.timing||{},o=e||{},a=o.actId||102103,i=r.navigationStart,m={duration:(new Date).getTime()-i,ttfb:r.responseStart-i,requestTime:r.responseEnd-r.requestStart},s=$.extend(!0,m,o);return"function"==typeof t&&t(1,a,s),s},o=function(){var e=window.performance;if(!e)return{msg:"not suport performance"};var t=e.timing||{},n=t.navigationStart,r={duration:(new Date).getTime()-n,ttfb:t.responseStart-n,requestTime:t.responseEnd-t.requestStart};
return r};n.exports={sendPerformanceLog:r,getPerformanceTiming:o}});
;define("wkcommon:widget/node_modules/@baidu/wenku-model-user/index.js",function(t,e,s){var o=window.$,r="wenkuData",i=function(){};i.prototype={constructor:i,data:{},res:{},onSuccess:{},onError:{},defer:{},status:{},injectLib:function(t){o=t||o},preOperate:function(t,e,s,r){o.isArray(this.onSuccess[t])?"before_fetch"===this.status[t]&&(this.status[t]="kicked_off"):(this.onSuccess[t]=[],this.onError[t]=[],this.defer[t]=[],this.status[t]="idle"),this.onSuccess[t].push(e),this.onError[t].push(s),this.defer[t].push(r)
},solveSuccess:function(t,e){for(var s=0;s<this.onSuccess[t].length;s++){var o=this.onSuccess[t][s];"function"==typeof o&&o(e)}for(var s=0;s<this.defer[t].length;s++){var r=this.defer[t][s]||{};"function"==typeof r.resolve&&r.resolve(e)}this.onSuccess[t]=[],this.defer[t]=[],window[t]=e,this.data[t]=e},solveError:function(t,e){for(var s=0;s<this.onError[t].length;s++){var o=this.onError[t][s];"function"==typeof o&&o(e)}for(var s=0;s<this.defer[t].length;s++){var r=this.defer[t][s]||{};"function"==typeof r.reject&&r.reject(e)
}this.onError[t]=[],this.defer[t]=[],window[t]=e,this.res[t]=e},solveCache:function(t,e){switch(this.status[t]){case"error":var s=this.res[t];this.solveError(t,s,e);break;case"success":var o=this.data[t];this.solveSuccess(t,o,e);break;default:var r=window[t];r&&this.solveSuccess(t,r,e)}},getUserInfo:function(t,e){var s=o.Deferred(),i=this,a=r+"userInfo",n=window[a]||i.data[a];return this.preOperate(a,t,e,s),void 0===n&&"idle"===i.status[a]?(i.status[a]="before_fetch",o.ajax({type:"get",cache:!1,url:"/user/interface/getuserinfo"}).done(function(t){if(t=t||{},i.res[a]=t,t&&t.status&&0===t.status.code){var e=t.data||{};
i.status[a]="success",i.solveSuccess(a,e)}else i.status[a]="error",i.solveError(a,t)}).fail(function(){i.status[a]="error",i.solveError(a,{})})):this.solveCache(a),s.promise()},isVipFreeDoc:function(t,e,s){var i=o.Deferred(),a=this;t=t||{};var n=t.docId||"",c=r+n+"isVipFreeDoc",u=window[c]||a.data[c];return this.preOperate(c,e,s,i),void 0===u&&"idle"===a.status[c]?(a.status[c]="before_fetch",o.ajax({type:"get",cache:!1,data:{doc_id:n},url:"/user/interface/getvipfreedoc"}).done(function(t){if(t&&t.status&&0===t.status.code){var e=t.data||{};
a.status[c]="success",a.solveSuccess(c,e.is_vip_free_doc)}else a.status[c]="error",a.solveError(c,t)}).fail(function(){a.status[c]="error",a.solveError(c,{})})):this.solveCache(c),i.promise()},getVipInfo:function(t,e){var s=o.Deferred(),i=this,a=r+"vipInfo",n=window[a]||i.data[a];return this.preOperate(a,t,e,s),void 0===n&&"idle"===i.status[a]?(i.status[a]="before_fetch",o.ajax({type:"get",cache:!1,data:{type:7},url:"/customer/interface/vipinfo"}).done(function(t){if(t&&t.status&&(0===t.status.code||1===t.status.code)){var e=t.data||{},s=e.vip_1||{},o=e.vip_2||{},r=e.vip_4||{};
e.isClassicVip=s.vip_status,e.isWenkuVip=s.vip_status&&s.flag,e.isWenkuEduVip=o.vip_status,e.isJiaoyuVip=r.vip_status,e.proDownloadTicket=0,s.vip_status&&s.pro_download_ticket&&(e.proDownloadTicket+=s.pro_download_ticket),o.vip_status&&o.pro_download_ticket&&(e.proDownloadTicket+=o.pro_download_ticket),r.vip_status&&r.pro_download_ticket&&(e.proDownloadTicket+=r.pro_download_ticket),e.normalDownloadTicket=0,s.vip_status&&s.normal_download_ticket&&(e.normalDownloadTicket+=s.normal_download_ticket),o.vip_status&&o.normal_download_ticket&&(e.normalDownloadTicket+=o.normal_download_ticket),r.vip_status&&r.normal_download_ticket&&(e.normalDownloadTicket+=r.normal_download_ticket),e.isVip=s.vip_status||o.vip_status||r.vip_status?!0:!1,i.status[a]="success",i.solveSuccess(a,e)
}else i.status[a]="error",i.solveError(a,t)}).fail(function(){i.status[a]="error",i.solveError(a,{})})):this.solveCache(a),s.promise()}};var a=new i;s.exports=a});